### ISSUE TITLE
1.1.0 release broken

### ISSUE THREAD

**Issue by martinheidegger** [baygeldin/fullwidth#3]
The current release 1.1.0 seems to not contain the compiled code (why does this library need babel?). When trying to use the latest package it throws following error:

``` JavaScript
Error: Cannot find module './fullwidth'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/.../node_modules/fullwidth/lib/index.js:7:18)
```

**Comment by baygeldin** [comment]
Thanks, fixed. As for babel, I just like to write ES6 :)
